# Site settings
title: Jatin-exe's blog
email: 
description: "Adventures of a Chaotically Calm person"
baseurl: ""
url: "http://jatin-exe.github.io"
twitter_username: jatin_exe
github_username:  jatin-exe

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: jekyll-theme-slate